"""reservations

Revision ID: 0d486b8d5f1d
Revises: fd74e6f48eed
Create Date: 2026-07-13 16:03:06.955932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d486b8d5f1d'
down_revision = 'fd74e6f48eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('item_type', sa.String(length=80), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('customer_email', sa.String(length=160), nullable=False),
    sa.Column('customer_phone', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.String(length=600), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservation_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservation_stripe_session_id'), ['stripe_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_stripe_session_id'))
        batch_op.drop_index(batch_op.f('ix_reservation_status'))
        batch_op.drop_index(batch_op.f('ix_reservation_deleted_at'))

    op.drop_table('reservation')
    # ### end Alembic commands ###
