"""media library

Revision ID: 502d134d19d3
Revises: bffe59074d0d
Create Date: 2026-07-11 19:12:51.892290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502d134d19d3'
down_revision = 'bffe59074d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=400), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=400), nullable=True),
    sa.Column('alt', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_kind'), ['kind'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_kind'))
        batch_op.drop_index(batch_op.f('ix_media_filename'))
        batch_op.drop_index(batch_op.f('ix_media_deleted_at'))

    op.drop_table('media')
    # ### end Alembic commands ###
