"""content types, field definitions, content entries

Revision ID: 99131d4872ac
Revises: 1cc96e2c81a7
Create Date: 2026-07-12 12:59:03.243896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99131d4872ac'
down_revision = '1cc96e2c81a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_type',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('is_singleton', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_type_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_type_slug'), ['slug'], unique=True)

    op.create_table('content_entry',
    sa.Column('content_type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('seo', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_type_id'], ['content_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_entry_content_type_id'), ['content_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_entry_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_entry_locale'), ['locale'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_entry_status'), ['status'], unique=False)

    op.create_table('field_definition',
    sa.Column('content_type_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('is_title', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_type_id'], ['content_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_definition_content_type_id'), ['content_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_field_definition_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_definition_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_field_definition_content_type_id'))

    op.drop_table('field_definition')
    with op.batch_alter_table('content_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_entry_status'))
        batch_op.drop_index(batch_op.f('ix_content_entry_locale'))
        batch_op.drop_index(batch_op.f('ix_content_entry_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_content_entry_content_type_id'))

    op.drop_table('content_entry')
    with op.batch_alter_table('content_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_type_slug'))
        batch_op.drop_index(batch_op.f('ix_content_type_deleted_at'))

    op.drop_table('content_type')
    # ### end Alembic commands ###
